"""ambertrace-rlvr — RLVR with AmberTrace verified platforms as the reward source.

Copyright (c) 2026 Ambertrace Labs Ltd. MIT Licensed.
"""

from __future__ import annotations

from .config import (
    DatasetConfig,
    EvalConfig,
    RunConfig,
    TrainingConfig,
    load_run_config,
)
from .corpus import (
    DecisionItem,
    corpus_stats,
    judgments_for,
    load_decision_corpus,
    write_decision_corpus,
)
from .cot_drift import (
    BACKTRACKING,
    HEDGING,
    VERIFIER_AWARENESS,
    DivergenceReport,
    LengthStats,
    LogOddsDiff,
    ProbeCorpus,
    ProbeTrace,
    channel_lengths,
    distinct_n,
    group_similarity,
    lexicon_rate,
    ngram_logodds_diff,
    think_stated_divergence,
    unsupported_fact_fraction,
)
from .deviation import (
    BALANCED,
    CAPITAL_ADEQUACY,
    SAFETY_FIRST,
    DeviationReport,
    ModelAnswer,
    OracleItem,
    PenaltyWeights,
    SeverityWeights,
    oracle_judgments,
    parse_model_answer,
    score_deviation,
    weighted_penalty,
)
from .domain import VerifiableDomain
from .eval_generator import (
    EvalCase,
    build_eval_items,
    vocabulary_from_verbs,
)
from .eval_oracle import (
    ABSTAIN,
    JudgmentSpec,
    LabelSpec,
    OracleJudgment,
)
from .evaluation import (
    EvalMetrics,
    EvalSample,
    Policy,
    ProbeReport,
    VerifierLike,
    compare_to_baseline,
    consistency,
    constant_policy,
    evaluate,
    evaluate_policy,
    malformed_policy,
    reward_hacking_score,
    run_policy,
)
from .faithfulness import (
    CandidateTrace,
    CurvePoint,
    CurveTrend,
    MonitorabilityComparison,
    compare_monitorability,
    curve_trend,
    faithfulness,
    faithfulness_curve,
    load_trajectory,
)
from .faithfulness_scorer import (
    RichScore,
    append_trajectory,
    consistency_score,
    score_batch_rich,
)
from .matrix import (
    AlignmentRow,
    AlignmentScore,
    ComplexityProfile,
    MatrixCAS,
    build_complexity_profile,
    confusion_pairs,
    render_alignment_score,
    render_cas_decomposition,
    render_matrix,
    render_profile,
    render_strata,
    run_alignment_matrix,
    run_model,
    score_alignment,
    score_by_action_count,
    score_cas,
    score_matrix_cas,
    score_strata,
)
from .model_backend import (
    LMStudioProvider,
    ModelBackendError,
    ModelProvider,
)
from .ood_drift import (
    POLICY_BLEED_LEXICON,
    OODBehaviouralMetrics,
    OODCheckpointSummary,
    format_leakage_rate,
    policy_bleed_rate,
    score_behavioural,
    score_ood_checkpoint,
    sycophancy_delta,
)
from .parsers import (
    CompletionParser,
    JSONBlockParser,
    ParsedCompletion,
    RegexBlockParser,
)
from .prompts import build_system_prompt, has_decision_block
from .quant_reasoning_sweep import (
    ReasoningLevelSummary,
    ReasoningRecord,
    classify_output,
    is_truncated_reasoning,
    render_reasoning_comparison,
    summarise_level,
    think_char_count,
)
from .quant_sweep import (
    QuantPoint,
    QuantSweep,
    precision_bits,
    render_quant_sweep,
    run_quant_sweep,
)
from .reporting import build_run_report, write_run_report
from .reports import AmberReport, FiredRule, RejectedFact
from .rewards import (
    DefaultRewardShaper,
    FactProvenanceChecker,
    RewardBreakdown,
    RewardShaper,
    SubstringProvenanceChecker,
    names_rule,
    reasoning_consistency,
)
from .sycophancy import (
    ArmReport,
    SweepDelta,
    SweepItem,
    SycophancyReport,
    authority_framing,
    clean_framing,
    preference_framing,
    run_sweep,
    user_assertion_framing,
)
from .testing import FakeVerifier
from .verifier import (
    REWARD_PROJECTION,
    AmberVerifier,
    RewardFunction,
    build_reward_function,
    score_one_item,
)

__version__ = "0.1.1"

__all__ = [
    "ABSTAIN",
    "BACKTRACKING",
    "BALANCED",
    "CAPITAL_ADEQUACY",
    "HEDGING",
    "POLICY_BLEED_LEXICON",
    "REWARD_PROJECTION",
    "SAFETY_FIRST",
    "VERIFIER_AWARENESS",
    "AlignmentRow",
    "AlignmentScore",
    "AmberReport",
    "AmberVerifier",
    "ArmReport",
    "CandidateTrace",
    "CompletionParser",
    "ComplexityProfile",
    "CurvePoint",
    "CurveTrend",
    "DatasetConfig",
    "DecisionItem",
    "DefaultRewardShaper",
    "DeviationReport",
    "DivergenceReport",
    "EvalCase",
    "EvalConfig",
    "EvalMetrics",
    "EvalSample",
    "FactProvenanceChecker",
    "FakeVerifier",
    "FiredRule",
    "JSONBlockParser",
    "JudgmentSpec",
    "LMStudioProvider",
    "LabelSpec",
    "LengthStats",
    "LogOddsDiff",
    "MatrixCAS",
    "ModelAnswer",
    "ModelBackendError",
    "ModelProvider",
    "MonitorabilityComparison",
    "OODBehaviouralMetrics",
    "OODCheckpointSummary",
    "OracleItem",
    "OracleJudgment",
    "ParsedCompletion",
    "PenaltyWeights",
    "Policy",
    "ProbeCorpus",
    "ProbeReport",
    "ProbeTrace",
    "QuantPoint",
    "QuantSweep",
    "ReasoningLevelSummary",
    "ReasoningRecord",
    "RegexBlockParser",
    "RejectedFact",
    "RewardBreakdown",
    "RewardFunction",
    "RewardShaper",
    "RichScore",
    "RunConfig",
    "SeverityWeights",
    "SubstringProvenanceChecker",
    "SweepDelta",
    "SweepItem",
    "SycophancyReport",
    "TrainingConfig",
    "VerifiableDomain",
    "VerifierLike",
    "__version__",
    "append_trajectory",
    "authority_framing",
    "classify_output",
    "build_complexity_profile",
    "build_eval_items",
    "build_reward_function",
    "build_run_report",
    "build_system_prompt",
    "channel_lengths",
    "clean_framing",
    "compare_monitorability",
    "compare_to_baseline",
    "confusion_pairs",
    "consistency",
    "consistency_score",
    "constant_policy",
    "corpus_stats",
    "curve_trend",
    "distinct_n",
    "evaluate",
    "evaluate_policy",
    "faithfulness",
    "faithfulness_curve",
    "format_leakage_rate",
    "group_similarity",
    "has_decision_block",
    "is_truncated_reasoning",
    "judgments_for",
    "lexicon_rate",
    "load_decision_corpus",
    "load_run_config",
    "load_trajectory",
    "malformed_policy",
    "names_rule",
    "ngram_logodds_diff",
    "oracle_judgments",
    "parse_model_answer",
    "policy_bleed_rate",
    "precision_bits",
    "preference_framing",
    "reasoning_consistency",
    "render_alignment_score",
    "render_reasoning_comparison",
    "render_cas_decomposition",
    "render_matrix",
    "render_profile",
    "render_quant_sweep",
    "render_strata",
    "reward_hacking_score",
    "run_alignment_matrix",
    "run_model",
    "run_policy",
    "run_quant_sweep",
    "run_sweep",
    "score_alignment",
    "score_batch_rich",
    "score_behavioural",
    "score_by_action_count",
    "score_cas",
    "score_deviation",
    "score_matrix_cas",
    "score_one_item",
    "score_ood_checkpoint",
    "score_strata",
    "summarise_level",
    "sycophancy_delta",
    "think_char_count",
    "think_stated_divergence",
    "unsupported_fact_fraction",
    "user_assertion_framing",
    "vocabulary_from_verbs",
    "weighted_penalty",
    "write_decision_corpus",
    "write_run_report",
]
