"""ambertrace-rlvr — RLVR with AmberTrace verified platforms as the reward source.

Copyright (c) 2026 Ambertrace Labs Ltd. MIT Licensed.
"""

from __future__ import annotations

from .config import (
    DatasetConfig,
    EvalConfig,
    RunConfig,
    TrainingConfig,
    load_run_config,
)
from .corpus import (
    DecisionItem,
    corpus_stats,
    judgments_for,
    load_decision_corpus,
    write_decision_corpus,
)
from .eval_generator import (
    EvalCase,
    build_eval_items,
    vocabulary_from_verbs,
)
from .matrix import (
    AlignmentRow,
    AlignmentScore,
    ComplexityProfile,
    MatrixCAS,
    build_complexity_profile,
    confusion_pairs,
    render_alignment_score,
    render_cas_decomposition,
    render_matrix,
    render_profile,
    render_strata,
    run_alignment_matrix,
    run_model,
    score_alignment,
    score_by_action_count,
    score_cas,
    score_matrix_cas,
    score_strata,
)
from .quant_sweep import (
    QuantPoint,
    QuantSweep,
    precision_bits,
    render_quant_sweep,
    run_quant_sweep,
)
from .deviation import (
    BALANCED,
    CAPITAL_ADEQUACY,
    SAFETY_FIRST,
    DeviationReport,
    ModelAnswer,
    OracleItem,
    PenaltyWeights,
    SeverityWeights,
    oracle_judgments,
    parse_model_answer,
    score_deviation,
    weighted_penalty,
)
from .domain import VerifiableDomain
from .faithfulness import (
    CandidateTrace,
    CurvePoint,
    CurveTrend,
    MonitorabilityComparison,
    compare_monitorability,
    curve_trend,
    faithfulness,
    faithfulness_curve,
    load_trajectory,
)
from .eval_oracle import (
    ABSTAIN,
    JudgmentSpec,
    LabelSpec,
    OracleJudgment,
)
from .evaluation import (
    EvalMetrics,
    EvalSample,
    Policy,
    ProbeReport,
    VerifierLike,
    compare_to_baseline,
    constant_policy,
    consistency,
    evaluate,
    evaluate_policy,
    malformed_policy,
    reward_hacking_score,
    run_policy,
)
from .model_backend import (
    LMStudioProvider,
    ModelBackendError,
    ModelProvider,
)
from .parsers import (
    CompletionParser,
    JSONBlockParser,
    ParsedCompletion,
    RegexBlockParser,
)
from .prompts import build_system_prompt, has_decision_block
from .sycophancy import (
    ArmReport,
    SweepDelta,
    SweepItem,
    SycophancyReport,
    authority_framing,
    clean_framing,
    preference_framing,
    run_sweep,
    user_assertion_framing,
)
from .reporting import build_run_report, write_run_report
from .reports import AmberReport, FiredRule, RejectedFact
from .rewards import (
    DefaultRewardShaper,
    FactProvenanceChecker,
    RewardBreakdown,
    RewardShaper,
    SubstringProvenanceChecker,
)
from .testing import FakeVerifier
from .verifier import AmberVerifier, RewardFunction, build_reward_function

__version__ = "0.1.1"

__all__ = [
    "VerifiableDomain",
    "load_run_config",
    "RunConfig",
    "TrainingConfig",
    "DatasetConfig",
    "EvalConfig",
    "CompletionParser",
    "ParsedCompletion",
    "JSONBlockParser",
    "RegexBlockParser",
    "AmberReport",
    "FiredRule",
    "RejectedFact",
    "RewardShaper",
    "RewardBreakdown",
    "DefaultRewardShaper",
    "FactProvenanceChecker",
    "SubstringProvenanceChecker",
    "AmberVerifier",
    "RewardFunction",
    "build_reward_function",
    "FakeVerifier",
    "build_system_prompt",
    "has_decision_block",
    "build_run_report",
    "write_run_report",
    "EvalSample",
    "EvalMetrics",
    "Policy",
    "VerifierLike",
    "evaluate",
    "evaluate_policy",
    "run_policy",
    "constant_policy",
    "malformed_policy",
    "compare_to_baseline",
    "consistency",
    "ProbeReport",
    "reward_hacking_score",
    "OracleJudgment",
    "JudgmentSpec",
    "LabelSpec",
    "ABSTAIN",
    "DeviationReport",
    "ModelAnswer",
    "OracleItem",
    "parse_model_answer",
    "score_deviation",
    "oracle_judgments",
    "SweepItem",
    "SweepDelta",
    "ArmReport",
    "SycophancyReport",
    "run_sweep",
    "clean_framing",
    "authority_framing",
    "user_assertion_framing",
    "preference_framing",
    "faithfulness",
    "CandidateTrace",
    "CurvePoint",
    "CurveTrend",
    "MonitorabilityComparison",
    "faithfulness_curve",
    "curve_trend",
    "compare_monitorability",
    "load_trajectory",
    "ModelProvider",
    "LMStudioProvider",
    "ModelBackendError",
    "DecisionItem",
    "load_decision_corpus",
    "write_decision_corpus",
    "judgments_for",
    "corpus_stats",
    "EvalCase",
    "build_eval_items",
    "vocabulary_from_verbs",
    "AlignmentRow",
    "run_model",
    "score_alignment",
    "run_alignment_matrix",
    "render_matrix",
    "score_strata",
    "render_strata",
    "confusion_pairs",
    "PenaltyWeights",
    "SeverityWeights",
    "SAFETY_FIRST",
    "BALANCED",
    "CAPITAL_ADEQUACY",
    "weighted_penalty",
    "ComplexityProfile",
    "build_complexity_profile",
    "render_profile",
    "score_by_action_count",
    "AlignmentScore",
    "MatrixCAS",
    "score_cas",
    "score_matrix_cas",
    "render_cas_decomposition",
    "render_alignment_score",
    "QuantSweep",
    "QuantPoint",
    "run_quant_sweep",
    "render_quant_sweep",
    "precision_bits",
    "__version__",
]
